### ISSUE TITLE
Non-fuzzy based searching proposal

### ISSUE THREAD

**Issue by jesse-c** [uptech/alt#36]
`alt` currently uses fuzzy-based searching based on the filename with scoring. Some languages, like Elixir [1], have conventions for test file locations. What if there was introduced other heuristics? E.g. if an exact match—based on a language's conventions—exists, then return that.

Implementation wise it could be as simple as checking if the file exists, which I can't imagine lowering performance. If anything, this fast return could increase performance as it could skip the fuzzy-based searching since an exact known match was found.

If so, would you be open to a PR that implements this?

The motivation for this was that I wanted to (optionally) create a test file if it didn't already exist when I try and use `alt`. If the "known file by convention" heuristic was there, then I could do that.

[1] `/lib/animal/giraffes/giraffe.ex` → `/test/animal/giraffes/giraffe_test.exs`

**Comment by drewdeponte** [comment]
@jesse-c I think some of what you are describing is already happing in alt. Let me give a high level explanation of what is happening in alt currently.

1. it takes the path provided on the command line and gets the filename minus any extensions and minus any test words
2. then it filters the possible paths down to ones that contain this filename (minus extension and test words)
3. then it filters the possible paths down ones that classify as tests if the given path does not classify as a test file and vice versa if the given path doesn't classify as a test file
4. the remaining possible paths are then scored around similarity and the value with the highest similarity scoring is returned as the alternate

**Note:** There are ways to filter the possible paths down by using the `-` file name in the command line args and using some external program to filter possible paths prior to them getting to `alt`. An example of this might be using `find` to filter possible paths and then piping them to `alt`.

The reason that `alt` is designed this way is because previously I created a Vim plugin purely based on heuristics as you are describing. This did have the benefit of facilitating the creation of files when they were missing. However, it had the major problem of heuristics from one framework colliding with those of other frameworks / languages and not being able to properly distinguish between them.

It became clear that this was unavoidable with basic heuristics. Therefore, I created `alt` which was initially just based on the scoring with out what I think of as the pre-filtering based on classification of a path being a test file or not. **Note:** this classification of a test file is based on heuristics like you are describing which exists here, https://github.com/uptech/alt/blob/main/src/alt/path/classification/mod.rs . This has the specific tests for Elixir to make sure it handles that case.

```rust
    // Elixir ExUnit

    #[test]
    fn is_test_file_detects_elixir_exunit_files() {
        let s = String::from("test/lib/my_awesome_app/supervisor_test.exs");
        assert_eq!(is_test_file(&s), true);
    }

    #[test]
    fn is_test_file_does_not_detect_elixir_implementation_files() {
        let s = String::from("lib/my_awesome_app/supervisor.ex");
        assert_eq!(is_test_file(&s), false);
    }
```

It looks like exactly the case you are talking about.

So if you are in an implementation file and try to use `alt` to get the alternate and it comes back with no alternate then you could create the file or if you are in the test file and try to use `alt` to find the implementation file and it comes back with no alternate you could create the implementation file.

This however would require having the following:

- know if the given path is classified as a test file or not (alt knows this)
- know if there is a matching alternate path in the possible paths (alt knows this, but it is also possible that alt can get it wrong because there is another path that has enough similarity to the path)
- know which framework/language heuristic to use to create the alternate path (alt does **NOT** know this because there is overlap between languages and frameworks that alt supports)

So I think for something like this to work the tool would have to become much more aware of the idea of projects and other files in the project directory to help identify which heuristic should be used. Through my work with vim-open-alternate I know that this isn't even fully possible because even within certain tech stacks there are overlapping/competing heuristics and there is no way to know in certain cases which heuristic to use.

Which means the tool would have to introduce some sort of configuration system to facilitate the user explicitly configuring which heuristic should be used.

**Comment by jesse-c** [comment]
Firstly, thank you for the very detailed response! What you've explained makes sense. I'll let it be for now or come up with a quick solution for my immediate need at my day job.

I'll close this as well, and I'll see if I think of anything useful, and I'll pay attention to `alt` releases to see how things go in the future.
